from typing import Protocol


class IUserRepository(Protocol):
    def get_by_id(self, user_id: int) -> dict | None: ...
    def get_all(self) -> list[dict]: ...


class IProductRepository(Protocol):
    def get_by_id(self, product_id: int) -> dict | None: ...
    def get_all(self) -> list[dict]: ...
